ViewsBanking/Models/Pago.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ViewsBanking.Models
{
    public partial class Pago
    {
        public int Codigo { get; set; }
        public int CodigoServicio { get; set; }
        public int CodigoCuenta { get; set; }
        public int CodigoMoneda { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal Monto { get; set; }

        public virtual Cuenta Cuenta { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}

ViewsBanking/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ViewsBanking.Managers;
using ViewsBanking.Models;

namespace ViewsBanking.Controllers
{
    public class PagoController : Controller
    {
        // GET: Pago
        public async Task<ActionResult> GetAll(string token)
        {
            PagoManager manager = new PagoManager();
            IEnumerable<Pago> list= await manager.GetAll(token);
            return View(list);
        }
        
        public ActionResult Borrar(int id) {
            return View();
        }
    }
}

ViewsBanking/Views/Pago/GetAll.cshtml
@model IEnumerable<ViewsBanking.Models.Pago>

@{
    ViewBag.Title = "GetAll";
}

<head>
    <title>Pago</title>
</head>
<h2>GetAll</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodigoServicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodigoCuenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodigoMoneda)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaHora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodigoServicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodigoCuenta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodigoMoneda)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaHora)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Monto)
        </td>
        <td>
            @Html.ActionLink("Borrar","Borrar","Pago",new {item.Codigo},null)
            @Html.ActionLink("Delete", "Delete", new { item.Codigo })
        </td>
    </tr>
}

</table>